links:
  "Photography": /photography/
  "@oncletom": https://twitter.com/oncletom
  "GitHub": https://github.com/oncletom
  "RSS Feed": /feed/

less:
  paths:
    - node_modules/css.oncletom.io/src/less
    - node_modules/bootstrap/less
