description: >
  Hello, I'm **Thomas Parisot**, a frenchman with web development, collaborative work and user experience skills.
author: Thomas Parisot
email: hi@oncletom.io
disqus_shortname: oncletom

graph:
  twitter:        oncletom
  pgp:            "https://keybase.io/oncletom/pgp_keys.asc?fingerprint=46637e267871df7f255788ee893c87dfb3335e7e"
  mastodon:       https://framapiaf.org/@oncletom
webmentions:
  url: https://webmention.io/oncletom.io
  features:
    pingback:   xmlrpc
    webmention: webmention

summary:
  work: >
    I combine web development, UX research and human-centered agile practices
    to put people at ease, to create a shared understanding of the _whys_ and the _whats_
    and to move from ideas to prototyping then to production.

links:
  - label: Writings
    href: /
  - label: Livre Node.js
    href: /node.js/
    lang: fr
  - label: Presentations
    href: /talks/
  - label: Reading Notes
    href: /reading-notes/
  - label: Photography
    href: /photography/
  - label: About
    href: /about/
  # - label: My values
  #   href: /about/values/
  # - label: My mission
  #   href: /about/mission/

less:
  layouts:
    series-day-to-day:
      - assets/css/series/day-to-day.css
    series-default:
      - assets/css/series/default.css
  paths:
    - source/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-oncletom/source/less
    - node_modules/hexo-theme-oncletom/node_modules
    - node_modules
