description: |
  Hey, I'm **Thomas** Parisot, a french **software designer**.

  Recently, I have been up to writing a book, team facilitation, Node.js programming and user research.

  I am **nomadic at the moment** • been a Londoner for 5 years and a Bordeaux chap for almost 20 years.

links:
  - namespace: blog
    label: Blog
    href: /
  - namespace: books
    label: Node.js
    href: /node.js/
  - namespace: talks
    label: Talks
    href: /talks/
  - namespace: reading-notes
    label: Reading Notes
    href: /reading-notes/
  - namespace: photography
    label: Photography
    href: /photography/
  - namespace: about
    label: About
    href: /slash-me/

less:
  layouts:
    series-day-to-day:
      - assets/css/series/day-to-day.css
    series-default:
      - assets/css/series/default.css
  paths:
    - source/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-oncletom/source/less
    - node_modules/hexo-theme-oncletom/node_modules
    - node_modules
