description: >
  Hello, I'm Thomas Parisot, a french web developer with team facilitation and user research skills.
  [My mission](/about/mission/) is to reinforce replicable, sustainable and open dynamics which benefit to citizens.
  My values are [Nature, Love and Autonomy](/about/values/).

links:
  - namespace: blog
    label: Home
    href: /
  - namespace: books
    label: Publications
    href: /publications/
  - namespace: talks
    label: Presentations
    href: /talks/
  - namespace: reading-notes
    label: Reading Notes
    href: /reading-notes/
  - namespace: photography
    label: Photography
    href: /photography/
  - namespace: about
    label: About
    href: /about/

less:
  layouts:
    series-day-to-day:
      - assets/css/series/day-to-day.css
    series-default:
      - assets/css/series/default.css
  paths:
    - source/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-oncletom/source/less
    - node_modules/hexo-theme-oncletom/node_modules
    - node_modules
