links:
  - namespace: blog
    label: Blog
    href: /
  - namespace: books
    label: Node.js
    href: /node.js/
  - namespace: talks
    label: Talks
    href: /talks/
  - namespace: reading-notes
    label: Reading Notes
    href: /reading-notes/
  - namespace: photography
    label: Photography
    href: /photography/
  - namespace: about
    label: About
    href: /slash-me/

less:
  layouts:
    series-day-to-day:
      - assets/css/series/day-to-day.css
    series-default:
      - assets/css/series/default.css
  paths:
    - node_modules/css.oncletom.io/src/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-oncletom/node_modules
    - node_modules
